[project]
name = "pytube"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "audio-separator>=0.39.1",
    "onnxruntime>=1.23.1",
    "streamlit>=1.24.1",
    "pytubefix>=10.0.0",
]
